forge 'https://forge.puppet.com'
# mod 'aboe/chrony', '0.3.2'
mod 'bodgit-bodgitlib', '2.0.1'
# mod 'bodgit-dbus', '2.0.1'
mod 'herculesteam-augeasproviders', '2.4.1'
mod 'herculesteam/augeasproviders_base', '2.1.0'
mod 'herculesteam/augeasproviders_core', '2.6.0'
mod 'herculesteam/augeasproviders_pam', '2.2.1'
mod 'herculesteam/augeasproviders_ssh', commit: 'e4eee3726d0472cba1d2d66a2d09031f1d100914', git: 'https://github.com/hercules-team/augeasproviders_ssh'
mod 'inkblot/ipcalc', '2.2.0'
# mod 'MiamiOH-pam_access', '1.0.2'
mod 'ncsa/pam_access', tag: 'v1.0.3', git: 'https://github.com/ncsa/puppet-pam_access'
mod 'ncsa/profile_additional_packages', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_additional_packages'
mod 'ncsa/profile_additional_yumrepos', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_additional_yumrepos'
mod 'ncsa/profile_allow_ssh_from_bastion', tag: 'v0.2.1', git: 'https://github.com/ncsa/puppet-profile_allow_ssh_from_bastion'
# mod 'ncsa/profile_chrony', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_chrony'
# mod 'ncsa/profile_email', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_email'
# mod 'ncsa/profile_firewall', tag: 'v1.0.1', git: 'https://github.com/ncsa/puppet-profile_firewall'
mod 'ncsa/profile_monitoring', tag: 'v0.1.3', git: 'https://github.com/ncsa/puppet-profile_monitoring'
mod 'ncsa/profile_motd', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_motd'
mod 'ncsa/profile_pam_access', tag: 'v0.0.4', git: 'https://github.com/ncsa/puppet-profile_pam_access'
# mod 'ncsa/profile_puppet_master', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_puppet_master'
mod 'ncsa/profile_sudo', tag: 'v0.1.1', git: 'https://github.com/ncsa/puppet-profile_sudo'
mod 'ncsa/profile_system_auth', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_system_auth'
mod 'ncsa/profile_timezone', tag: 'v0.2.1', git: 'https://github.com/ncsa/puppet-profile_timezone'
mod 'ncsa/profile_virtual', tag: 'v0.1.0', git: 'https://github.com/ncsa/puppet-profile_virtual'
mod 'ncsa/sshd', tag: 'v0.3.0', git: 'https://github.com/ncsa/puppet-sshd'
mod 'ncsa/sssd', tag: 'v3.0.0', git: 'https://github.com/ncsa/puppet-sssd'
mod 'ncsa/telegraf', tag: 'v3.1.1', git: 'https://github.com/ncsa/puppet-telegraf.git'
# mod 'puppet/epel', '3.0.1'
# mod 'puppet/python', '4.1.1'
# mod 'puppet/rsyslog', '5.0.1'
# mod 'puppetlabs/apt', '7.3.0'
mod 'puppetlabs/concat', '6.4.0'
mod 'puppetlabs/firewall', '2.5.0'
#mod 'puppetlabs-firewall', '2.8.0'
# mod 'puppetlabs/inifile', '4.1.0'
# mod 'puppetlabs/mailalias_core', '1.0.6'
mod 'puppetlabs/stdlib', '6.3.0'
# mod 'puppetlabs/translate', '2.1.0'
# mod 'puppetlabs/xinetd', '3.3.0'
mod 'richardc-datacat', '0.6.2'
# mod 'saz/limits', '3.0.4'
mod 'saz/sudo', '6.0.0'
mod 'saz/timezone', '6.1.0'
# mod 'sharumpe-tcpwrappers', '1.0.4'
#mod 'sharumpe-tcpwrappers', tag: '1.0.7', git: 'https://github.com/sharumpe/puppet-tcpwrappers.git'
#mod 'ffquintella-tcpwrappers', tag: '1.0.7', git: 'https://github.com/ffquintella/puppet-tcpwrappers.git'
mod 'thrnio-ip', '1.0.1'
mod 'woodsbw/augeasfacter', commit: '9aea81311d277ed7ff1e8f2d4f79d13cd25f6ded', git: 'https://github.com/woodsbw/augeasfacter'
