# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    # stdlib: "puppetlabs/stdlib"
  repositories:
    ## START PUPPET-LITMUS DEPENDENCIES ##
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    ## END PUPPET-LITMUS DEPENDENCIES ##
